### ISSUE TITLE
Questions about dataset

### ISSUE THREAD

**Issue by GooDrYu** [universome/stylegan-v#5]
Hi! Congratulations to your great job!
I am trying to run your code with the FFS dataset, but I met some problems.
I firstly download the FFS videos from the official website, and divide the videos into frames and extract face images to form a dataset as the same format as yours.
Then, how to let the training script know where the dataset is ？ I tried to directly modiy the "path: data/${dataset.name}" configuration in /stylegan-v/configs/training/base.yaml to "path: my_dataset_path", but it will raise error. 
Should I repalce all the related dataset configurations with my own dataset path?
e.g.  /stylegan-v/configs/env/base.yaml/datasets_dir: ~
       /stylegan-v/configs/dataset/base.yaml/path: data/${dataset.name}

**Comment by universome** [comment]
Hi, thank you! Could you tell, which error did it raise?
If you store your datasets zip archives in `/path/to/my/datasets` (this means that your FFS dataset has the path `/path/to/my/datasets/ffs_256_unstable.zip`), then you should change the `path` attribute in `stylegan-v/configs/dataset/base.yaml` from `data/${dataset.name}.zip` to `/path/to/my/datasets/${dataset.name}.zip`. 

If your FFS archive name is smth like `FFS_DATASET.zip` rather than `ffs_256_unstable.zip`, then you should change its name from `ffs_${dataset.resolution}_unstable` to `FFS_DATASET` in `stylegan-v/configs/dataset/ffs.yaml`

**Comment by GooDrYu** [comment]
> Hi, thank you! Could you tell, which error did it raise? If you store your datasets zip archives in `/path/to/my/datasets` (this means that your FFS dataset has the path `/path/to/my/datasets/ffs_256_unstable.zip`), then you should change the `path` attribute in `stylegan-v/configs/dataset/base.yaml` from `data/${dataset.name}.zip` to `/path/to/my/datasets/${dataset.name}.zip`.
> 
> If your FFS archive name is smth like `FFS_DATASET.zip` rather than `ffs_256_unstable.zip`, then you should change its name from `ffs_${dataset.resolution}_unstable` to `FFS_DATASET` in `stylegan-v/configs/dataset/ffs.yaml`

Thank you! it worked

**Comment by universome** [comment]
Welcome! I am closing this issue then.
Feel free to re-open it if you'll have any further questions or just open a new one.
